name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Change this to your branch name
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the Node.js version compatible with your project

      - name: Install dependencies
        run: npm install
        working-directory: ./todo-react  # Update with your React app directory

      - name: Build project
        run: npm run build
        working-directory: ./todo-react  # Update with your React app directory

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Auto-injected by GitHub
          action: 'upload'
          app_location: './todo-react'  # Update with your React app directory
          output_location: '.next'  # Update with your build directory
